version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000" # Maps frontend container's port 3000 to host's port 3001
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    stdin_open: true # Keeps stdin open for React development server
    tty: true # Ensures terminal display in Docker for frontend
    command: npm start # Ensures frontend runs in development mode

volumes:
  mongo_data:
